export interface Product {
  id: string;
  name: string;
  category: 'Cosmetics & Beauty' | 'Groceries & Food';
  price: number;
  description: string;
  image: string;
  tag?: string;
  featured?: boolean;
}

export const CATEGORIES = ['All', 'Cosmetics & Beauty', 'Groceries & Food'] as const;

export const PRODUCTS: Product[] = [
  // ─── Cosmetics & Beauty ─────────────────────────────────────────────────────
  {
    id: 'cos-01',
    name: 'Premium Matte Lipstick Set',
    category: 'Cosmetics & Beauty',
    price: 25.00,
    description: 'A luxurious set of six highly pigmented matte lipsticks. Long-lasting, velvet-smooth formula in classic and modern shades. Dermatologist tested and safe for all skin tones.',
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&auto=format&fit=crop&q=80',
    tag: 'Best Seller',
    featured: true,
  },
  {
    id: 'cos-02',
    name: 'Organic Glow Skin Serum',
    category: 'Cosmetics & Beauty',
    price: 40.00,
    description: 'Infused with Vitamin C and natural botanical extracts to brighten, hydrate, and restore your skin\'s natural radiant glow. Lightweight, fast-absorbing formula.',
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&auto=format&fit=crop&q=80',
    tag: 'Trending',
    featured: true,
  },
  {
    id: 'cos-03',
    name: 'Luxury Oud & Fragrance Mist',
    category: 'Cosmetics & Beauty',
    price: 55.00,
    description: 'An elegant blend of rich agarwood oud, warm amber, and light floral notes. A premium, long-lasting signature scent crafted in the Middle Eastern tradition.',
    image: 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=600&auto=format&fit=crop&q=80',
    tag: 'Popular',
    featured: true,
  },
  {
    id: 'cos-04',
    name: 'Hydrating Rose Face Mask',
    category: 'Cosmetics & Beauty',
    price: 18.00,
    description: 'Deep-cleansing rose petal sheet mask enriched with hyaluronic acid and collagen peptides. Restores elasticity and leaves skin supple and dewy in 20 minutes.',
    image: 'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600&auto=format&fit=crop&q=80',
    tag: 'New Arrival',
    featured: true,
  },
  {
    id: 'cos-05',
    name: 'Pro HD Foundation Stick',
    category: 'Cosmetics & Beauty',
    price: 32.00,
    description: 'A full-coverage, long-wear foundation stick available in 40 shades. Transfer-proof, water-resistant formula that blends seamlessly for a flawless, matte finish.',
    image: 'https://images.unsplash.com/photo-1583241800698-e8ab01830a17?w=600&auto=format&fit=crop&q=80',
    tag: 'Editor\'s Pick',
    featured: false,
  },
  {
    id: 'cos-06',
    name: 'Volumizing Mascara & Liner Kit',
    category: 'Cosmetics & Beauty',
    price: 22.00,
    description: 'Drama-defining mascara with a fiber brush for maximum volume and curl, bundled with a precision liquid liner pen for a bold, long-lasting cat-eye look.',
    image: 'https://images.unsplash.com/photo-1631214500004-08cd70617a9b?w=600&auto=format&fit=crop&q=80',
    tag: 'Bundle',
    featured: false,
  },
  {
    id: 'cos-07',
    name: 'Argan Oil Hair Treatment',
    category: 'Cosmetics & Beauty',
    price: 28.00,
    description: '100% pure Moroccan argan oil for hair repair, frizz control, and ultimate shine. A few drops transforms dry, brittle hair into lustrous, silk-smooth strands.',
    image: 'https://images.unsplash.com/photo-1519235624215-85175d5eb36e?w=600&auto=format&fit=crop&q=80',
    tag: 'Natural',
    featured: true,
  },
  {
    id: 'cos-08',
    name: 'Rose Gold Eyeshadow Palette',
    category: 'Cosmetics & Beauty',
    price: 35.00,
    description: 'A 18-pan eyeshadow palette featuring a curated range of warm rose golds, burgundies, and champagnes. Buttery-smooth, ultra-blendable formula for day-to-night looks.',
    image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&auto=format&fit=crop&q=80',
    tag: 'Glamour',
    featured: false,
  },
  {
    id: 'cos-09',
    name: 'SPF 50 Daily Sunscreen Serum',
    category: 'Cosmetics & Beauty',
    price: 30.00,
    description: 'Lightweight, invisible SPF 50 serum that protects against UVA and UVB rays. Non-greasy formula with Niacinamide for simultaneous sun protection and skin brightening.',
    image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
    tag: 'Essential',
    featured: false,
  },

  // ─── Groceries & Food ───────────────────────────────────────────────────────
  {
    id: 'groc-01',
    name: 'Premium Basmati Rice (5kg)',
    category: 'Groceries & Food',
    price: 12.00,
    description: 'Extra-long grain premium basmati rice. Double-polished and aged to perfection for a fragrant and fluffy texture in every serving.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop&q=80',
    tag: 'Essential',
    featured: true,
  },
  {
    id: 'groc-02',
    name: 'Pure Sunflower Cooking Oil (5L)',
    category: 'Groceries & Food',
    price: 14.00,
    description: '100% pure refined sunflower oil. Rich in Vitamin E, cholesterol-free, and ideal for all types of cooking and deep frying.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    tag: 'Essential',
    featured: false,
  },
  {
    id: 'groc-03',
    name: 'Organic Somali Tea Spices (Xawaash)',
    category: 'Groceries & Food',
    price: 5.00,
    description: 'Authentic Somali tea spice blend featuring fresh cardamom, cinnamon, cloves, and ginger. Perfect for a warm, fragrant Somali Shaah.',
    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=600&auto=format&fit=crop&q=80',
    tag: 'Traditional',
    featured: true,
  },
  {
    id: 'groc-04',
    name: 'Premium Powdered Milk (2.5kg)',
    category: 'Groceries & Food',
    price: 22.00,
    description: 'Rich, creamy full-cream powdered milk. Fortified with essential vitamins and calcium for the whole family\'s daily nutrition needs.',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    tag: 'Popular',
    featured: false,
  },
  {
    id: 'groc-05',
    name: 'Wild Honey Jar (1kg)',
    category: 'Groceries & Food',
    price: 16.00,
    description: 'Raw, unfiltered wild honey harvested from pristine forests. Packed with natural antioxidants, enzymes, and rich floral flavor. No additives or preservatives.',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80',
    tag: 'Natural',
    featured: true,
  },
  {
    id: 'groc-06',
    name: 'Premium Dates Gift Box (1kg)',
    category: 'Groceries & Food',
    price: 20.00,
    description: 'Medjool and Sukkari dates hand-selected from the finest farms. Soft, caramel-sweet, and deeply nourishing. Perfect for Ramadan or gifting.',
    image: 'https://images.unsplash.com/photo-1591812698093-7ec13adbb3e7?w=600&auto=format&fit=crop&q=80',
    tag: 'Gift Set',
    featured: true,
  },
  {
    id: 'groc-07',
    name: 'Organic Black Seed Oil (500ml)',
    category: 'Groceries & Food',
    price: 18.00,
    description: 'Cold-pressed Nigella sativa black seed oil — a cornerstone of traditional medicine. Supports immunity, digestion, and overall wellness naturally.',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&auto=format&fit=crop&q=80',
    tag: 'Wellness',
    featured: false,
  },
  {
    id: 'groc-08',
    name: 'Somali Suqaar Spice Blend',
    category: 'Groceries & Food',
    price: 7.00,
    description: 'A signature spice mix for the classic Somali suqaar (stir-fried meat) dish. A harmonious blend of cumin, coriander, black pepper, and turmeric.',
    image: 'https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&auto=format&fit=crop&q=80',
    tag: 'Traditional',
    featured: false,
  },
  {
    id: 'groc-09',
    name: 'Premium Green Tea Collection',
    category: 'Groceries & Food',
    price: 13.00,
    description: 'A curated selection of premium whole-leaf green teas sourced from East Asia. Antioxidant-rich, delicate flavor, and a clean, refreshing finish.',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&auto=format&fit=crop&q=80',
    tag: 'Wellness',
    featured: false,
  },
  {
    id: 'groc-10',
    name: 'Organic Extra Virgin Olive Oil (1L)',
    category: 'Groceries & Food',
    price: 24.00,
    description: 'First cold-press extra virgin olive oil from certified organic Mediterranean groves. Rich, fruity flavor with a robust finish. Ideal for cooking and dressing.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    tag: 'Organic',
    featured: false,
  },
];

export const FEATURED_PRODUCTS = PRODUCTS.filter((p) => p.featured).slice(0, 9);
